version: '3.8'
services:
  go-app:
    container_name: go-rest-api-with-gin-and-gorm
    build: .
    volumes:
      - .:/app:cached
    ports:
      - 8080:8080
    command: /bin/sh -c "while sleep 1000; do :; done"
    